### ISSUE TITLE
Connection refused.

### ISSUE THREAD

**Issue by ckhatton** [TheLindaProjectInc/Metrix#156]
I just thought I would share this as it might be a bug in the coding. Please run a fresh wallet sync to see if you can reenact the issue.

I have found a full sync with a fresh wallet hangs time to time on a block. You have to restart the daemon to get it working through the blocks again.

```
connect() to #.#.#.#:33820 failed after select(): Connection refused (111)
socket recv error Connection reset by peer (104)
```

Also this fatal error came up after leaving it stuck for hours...

```
************************
EXCEPTION: St13runtime_error
tinyformat: Not enough conversion specifiers in format string
Metrix in ProcessMessages()
```

Again, restarting the daemon got it working.

Both errors have occurred on two separate wallet setups. :octocat:

---

Linux x64 CLI wallet v3.4.0.0

**Comment by davidstoneham** [comment]
```
connect() to #.#.#.#:33820 failed after select(): Connection refused (111)
socket recv error Connection reset by peer (104)
```
Is a normal error which means the node on the other end was not available or rejected your connection request. This can happen for a variety of reasons e.g. there node might not be online, may have too many connections, you are on their ban list etc. This shouldn't cause any issues unless you can't connect to any peers.

For the syncing issue, your node shouldn't stop syncing unless you aren't connected to nodes that have more valid blocks than you. Are you able to confirm that you had active peers and their chain is longer than yours? I am unable to replicate this problem with the new HFS update but if you are continuing to encounter this then we will need your debug.log file to investigate further.

```
************************
EXCEPTION: St13runtime_error
tinyformat: Not enough conversion specifiers in format string
Metrix in ProcessMessages()
```
Is due to an incorrectly formatting logging statement in the code, thanks for reporting that and we'll try and hunt it down.

**Comment by ckhatton** [comment]
> Is a normal error which means the node on the other end was not available or rejected your connection request.

Okay fair enough. Thank you for explaining.

> Your node shouldn't stop syncing unless you aren't connected to nodes that have more valid blocks than you.

There were definitely active peers connected, whether their chain was longer than mine I can only assume. It would seem after leaving it a long time strange to not connect to a peer that a longer chain than mine. If you aren't able to replicate this issue, then I think it will be best ignored - If the issue arises again in the future, then I will report it again.

> [This is] due to an incorrectly formatting logging statement in the code.

Glad I found one bug 😊:thumbsup:

**Comment by davidstoneham** [comment]
```
************************
EXCEPTION: St13runtime_error
tinyformat: Not enough conversion specifiers in format string
Metrix in ProcessMessages()
```

has been resolved and the fix will be available in the next release
